### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by cloudcant** [Tukzlol/Dlive-Follow-Bot#1]
Random token from the list is wildin, iterate through em

```python
for x in range(len(tokens)): 
    token = (tokens[x]) 
```

**Comment by ledges** [comment]
> Random token from the list is wildin, iterate through em
> 
> ```python
> for x in range(len(tokens)): 
>     token = (tokens[x]) 
> ```

```py
tokens = open("./data/tokens.txt", "r").read().splitlines()

for x in tokens:
      print("token: %s", x)
```
